// features/group-creation/components/createGroupFlow.styles.ts
// Styles for the CreateGroupSheet wizard and its sub-components.

import { StyleSheet } from "react-native";

export const createStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  creatingOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 100,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingWrap: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
  },
  emptyText: {
    fontSize: 14,
    fontWeight: "500",
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  headerCenter: {
    flex: 1,
    marginRight: 12,
  },
  headerBackText: {
    padding: 4,
  },
  wizardContent: {
    paddingHorizontal: 20,
    paddingTop: 28,
  },
  wizardTitle: {
    fontWeight: "700",
    marginBottom: 16,
    textAlign: "center",
  },
  avatarPicker: {
    alignSelf: "center",
    marginBottom: 20,
    position: "relative",
  },
  avatarEditBadge: {
    position: "absolute",
    bottom: -4,
    right: -4,
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  fieldGroup: {
    gap: 8,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: "600",
  },
  fieldInput: {
    fontSize: 18,
    fontWeight: "500",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    textAlign: "left",
  },
  descInput: {
    fontSize: 14,
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    minHeight: 100,
    textAlign: "left",
  },
  fieldCharCount: {
    fontSize: 11,
    fontWeight: "500",
    textAlign: "right",
  },
  stickyBottom: {
    position: "absolute",
    left: 0,
    right: 0,
    paddingVertical: 6,
    paddingHorizontal: 20,
  },
  createBtn: {
    borderRadius: 20,
    paddingVertical: 12,
    alignSelf: "stretch",
    alignItems: "center",
  },
  createBtnText: {
    fontSize: 16,
    fontWeight: "700",
  },
  advancedContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 40,
  },
  advSectionTitle: {
    fontSize: 12,
    fontWeight: "500",
    marginBottom: 4,
  },
  advRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
  },
  advRowLabel: {
    fontSize: 15,
  },
  advRowValue: {
    fontSize: 14,
  },
  advRowSub: {
    fontSize: 11,
    marginTop: 2,
  },
  advToggle: {
    width: 34,
    height: 20,
    borderRadius: 10,
    justifyContent: "center",
    paddingHorizontal: 2,
  },
  nudgeChipsContainer: {
    paddingVertical: 8,
    paddingLeft: 12,
  },
  nudgeChipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  nudgeChip: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
  },
  advToggleKnob: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#fff",
    alignSelf: "flex-end",
  },
  advRowRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  sheetContent: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 32,
  },
  sheetTitle: {
    fontSize: 15,
    fontWeight: "600",
    textAlign: "center",
    paddingBottom: 12,
    marginBottom: 8,
    borderBottomWidth: 1,
  },
  sheetOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
  },
  sheetOptionLabel: {
    fontSize: 14,
  },
  sheetDoneBtn: {
    marginTop: 16,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: "center",
  },
  sheetDoneBtnText: {
    fontSize: 15,
    fontWeight: "600",
    textTransform: "capitalize",
  },
  avatarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 16,
    paddingBottom: 20,
  },
  avatarGridItem: {
    width: 64,
    height: 64,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.2)",
  },
  headerTitle: {
    fontWeight: "700",
    fontSize: 20,
    textAlign: "center",
  },
  headerDesc: {
    fontSize: 13,
    marginTop: 2,
    textAlign: "center",
  },
  continueBottomBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginBottom: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
  },
  continueBtn: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 5,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1,
    flexShrink: 0,
  },
  continueBtnText: {
    fontWeight: "700",
    fontSize: 12,
    flexShrink: 0,
  },
  content: {
    flex: 1,
  },
  contentInner: {
    paddingHorizontal: 16,
    paddingTop: 0,
    paddingBottom: 160,
  },
  leagueGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  leagueGridItem: {
    width: "48%",
    alignItems: "flex-start",
    padding: 12,
    borderRadius: 10,
    gap: 6,
  },
  leagueGridDot: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  leagueGridName: {
    fontSize: 12,
    fontWeight: "600",
  },
  leagueGridCountry: {
    fontSize: 10,
    fontWeight: "500",
    marginTop: -2,
  },
  gameGridAddBtn: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  leagueGridAddBtn: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  leagueGridBadge: {
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  leagueGridBadgeText: {
    fontSize: 10,
    fontWeight: "700",
  },
  listRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 8,
  },
  listRowDot: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  listRowInfo: {
    flex: 1,
    gap: 1,
  },
  listRowName: {
    fontSize: 14,
    fontWeight: "600",
  },
  listRowSub: {
    fontSize: 11,
    fontWeight: "500",
  },
  gameGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  gameGridCard: {
    width: "48%",
    padding: 10,
    borderRadius: 10,
    gap: 6,
  },
  gameGridTeams: {
    gap: 3,
    marginTop: 4,
  },
  gameGridTeamRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    overflow: "hidden",
  },
  gameGridDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
  },
  gameGridTeamName: {
    fontSize: 11,
    fontWeight: "600",
    flex: 1,
  },
  gameGridFooter: {
    gap: 3,
  },
  gameGridMeta: {
    fontSize: 10,
    fontWeight: "500",
  },
  gameGridTime: {
    fontSize: 10,
    fontWeight: "500",
  },
  leagueSection: {
    marginBottom: 6,
  },
  leagueHeader: {
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 6,
  },
  gameCard: {
    marginBottom: 10,
  },
  gameBody: {
    flexDirection: "row",
    alignItems: "center",
  },
  gameTeams: {
    flex: 1,
    gap: 4,
  },
  gameTeamRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  gameTeamDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
  },
  gameTeamName: {
    fontSize: 14,
    fontWeight: "500",
    flex: 1,
  },
  gameAddBtn: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  gameFooter: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 2,
    paddingLeft: 28,
  },
  gameFooterText: {
    fontSize: 10,
    fontWeight: "500",
  },
  gameFooterDot: {
    fontSize: 10,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginHorizontal: 12,
    marginVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: "rgba(0,0,0,0.04)",
    height: 34,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    padding: 0,
  },
  dateSliderWrap: {
    height: 46,
    zIndex: 1,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 6,
    elevation: 5,
  },
  dateRow: {
    paddingHorizontal: 12,
    alignItems: "center",
    paddingVertical: 10,
    gap: 6,
  },
  dateItem: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 14,
    borderWidth: 1,
  },
  dateText: {
    fontSize: 12,
    fontWeight: "600",
  },
  tabBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  tabRow: {
    flexDirection: "row",
    gap: 10,
  },
  tab: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingVertical: 8,
    borderRadius: 10,
  },
  tabLabel: {
    fontWeight: "600",
    fontSize: 12,
  },
  sortRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
  },
  sortBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  sortLabel: {
    fontSize: 12,
    fontWeight: "500",
  },
  viewModeBtn: {
    padding: 4,
  },
  sortSheet: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 34,
  },
  sortSheetTitle: {
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 20,
  },
  sortSheetItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 16,
  },
  sortSheetItemText: {
    fontSize: 17,
    fontWeight: "500",
  },
  sortSheetCancel: {
    alignItems: "center",
    marginTop: 16,
    paddingVertical: 12,
  },
  sortSheetCancelText: {
    fontSize: 16,
    fontWeight: "500",
  },
});
