// features/group-creation/components/createGroupFlow.styles.ts
// Styles for the CreateGroupSheet wizard and its sub-components.

import { StyleSheet } from "react-native";
import { spacing } from "@/lib/theme/spacing";
import { radius } from "@/lib/theme/radius";

export const createStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  creatingOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 100,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingWrap: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: spacing.xxl,
  },
  emptyText: {
    fontSize: 14,
    fontWeight: "500",
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.ms,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  headerCenter: {
    flex: 1,
    marginRight: spacing.ms,
  },
  headerBackText: {
    padding: spacing.xs,
  },
  wizardContent: {
    paddingHorizontal: spacing.ml,
    paddingTop: 28,
  },
  wizardTitle: {
    fontWeight: "700",
    marginBottom: spacing.md,
    textAlign: "center",
  },
  avatarPicker: {
    alignSelf: "center",
    marginBottom: spacing.ml,
    position: "relative",
  },
  avatarEditBadge: {
    position: "absolute",
    bottom: -4,
    right: -4,
    width: spacing.lg,
    height: spacing.lg,
    borderRadius: radius.full,
    justifyContent: "center",
    alignItems: "center",
  },
  fieldGroup: {
    gap: spacing.sm,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: "600",
  },
  fieldInput: {
    fontSize: 18,
    fontWeight: "500",
    paddingHorizontal: spacing.ms,
    paddingVertical: spacing.xs + 2,
    borderRadius: radius.md,
    textAlign: "left",
  },
  descInput: {
    fontSize: 14,
    marginTop: spacing.ms,
    paddingHorizontal: spacing.ms,
    paddingVertical: spacing.sm + 2,
    borderRadius: radius.md,
    minHeight: 100,
    textAlign: "left",
  },
  fieldCharCount: {
    fontSize: 11,
    fontWeight: "500",
    textAlign: "right",
  },
  stickyBottom: {
    position: "absolute",
    left: 0,
    right: 0,
    paddingVertical: spacing.xs + 2,
    paddingHorizontal: spacing.ml,
  },
  createBtn: {
    borderRadius: radius.xl,
    paddingVertical: spacing.ms,
    alignSelf: "stretch",
    alignItems: "center",
  },
  createBtnText: {
    fontSize: 16,
    fontWeight: "700",
  },
  advancedContent: {
    paddingHorizontal: spacing.ml,
    paddingTop: spacing.md,
    paddingBottom: spacing.xxl,
  },
  advSectionTitle: {
    fontSize: 12,
    fontWeight: "500",
    marginBottom: spacing.xs,
  },
  advRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: spacing.sm + 2,
  },
  advRowLabel: {
    fontSize: 15,
  },
  advRowValue: {
    fontSize: 14,
  },
  advRowSub: {
    fontSize: 11,
    marginTop: spacing.xxs,
  },
  advToggle: {
    width: 34,
    height: 20,
    borderRadius: radius.sm,
    justifyContent: "center",
    paddingHorizontal: spacing.xxs,
  },
  nudgeChipsContainer: {
    paddingVertical: spacing.sm,
    paddingLeft: spacing.ms,
  },
  nudgeChipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  nudgeChip: {
    paddingHorizontal: spacing.ml,
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
    borderWidth: 1,
  },
  advToggleKnob: {
    width: spacing.md,
    height: spacing.md,
    borderRadius: radius.s,
    backgroundColor: "#fff",
    alignSelf: "flex-end",
  },
  advRowRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  sheetContent: {
    paddingHorizontal: spacing.ml,
    paddingTop: spacing.ms,
    paddingBottom: spacing.xl,
  },
  sheetTitle: {
    fontSize: 15,
    fontWeight: "600",
    textAlign: "center",
    paddingBottom: spacing.ms,
    marginBottom: spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  sheetOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: spacing.md - 2,
  },
  sheetOptionLabel: {
    fontSize: 14,
  },
  sheetDoneBtn: {
    marginTop: spacing.md,
    paddingVertical: spacing.ms,
    borderRadius: radius.md,
    alignItems: "center",
  },
  sheetDoneBtnText: {
    fontSize: 15,
    fontWeight: "600",
    textTransform: "capitalize",
  },
  avatarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: spacing.md,
    paddingBottom: spacing.ml,
  },
  avatarGridItem: {
    width: 64,
    height: 64,
    borderRadius: radius.lg,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.2)",
  },
  headerTitle: {
    fontWeight: "700",
    fontSize: 20,
    textAlign: "center",
  },
  headerDesc: {
    fontSize: 13,
    marginTop: spacing.xxs,
    textAlign: "center",
  },
  continueBottomBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs + 2,
    marginBottom: spacing.ms,
    paddingVertical: spacing.sm + 2,
    borderRadius: radius.md,
    borderWidth: 1,
  },
  continueBtn: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 5,
    paddingVertical: spacing.xs + 2,
    paddingHorizontal: spacing.ms,
    borderRadius: radius.xl,
    borderWidth: 1,
    flexShrink: 0,
  },
  continueBtnText: {
    fontWeight: "700",
    fontSize: 12,
    flexShrink: 0,
  },
  content: {
    flex: 1,
  },
  contentInner: {
    paddingHorizontal: spacing.md,
    paddingTop: 0,
    paddingBottom: 160,
  },
  leagueGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  leagueGridItem: {
    width: "48%",
    alignItems: "flex-start",
    padding: spacing.ms,
    borderRadius: radius.md,
    gap: spacing.xs + 2,
  },
  leagueGridDot: {
    width: 36,
    height: 36,
    borderRadius: radius.lg,
  },
  leagueGridName: {
    fontSize: 12,
    fontWeight: "600",
  },
  leagueGridCountry: {
    fontSize: 10,
    fontWeight: "500",
    marginTop: -2,
  },
  gameGridAddBtn: {
    width: spacing.lg,
    height: spacing.lg,
    borderRadius: radius.full,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: spacing.sm,
  },
  leagueGridAddBtn: {
    position: "absolute",
    top: spacing.sm,
    right: spacing.sm,
    width: spacing.lg,
    height: spacing.lg,
    borderRadius: radius.full,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  leagueGridBadge: {
    minWidth: spacing.ml,
    height: spacing.ml,
    borderRadius: radius.sm,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.xs,
  },
  leagueGridBadgeText: {
    fontSize: 10,
    fontWeight: "700",
  },
  listRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm + 2,
    paddingVertical: spacing.sm,
  },
  listRowDot: {
    width: spacing.xl,
    height: spacing.xl,
    borderRadius: radius.full,
  },
  listRowInfo: {
    flex: 1,
    gap: 1,
  },
  listRowName: {
    fontSize: 14,
    fontWeight: "600",
  },
  listRowSub: {
    fontSize: 11,
    fontWeight: "500",
  },
  gameGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  gameGridCard: {
    width: "48%",
    padding: spacing.sm + 2,
    borderRadius: radius.md,
    gap: spacing.xs + 2,
  },
  gameGridTeams: {
    gap: 3,
    marginTop: spacing.xs,
  },
  gameGridTeamRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    overflow: "hidden",
  },
  gameGridDot: {
    width: spacing.md,
    height: spacing.md,
    borderRadius: radius.s,
  },
  gameGridTeamName: {
    fontSize: 11,
    fontWeight: "600",
    flex: 1,
  },
  gameGridFooter: {
    gap: 3,
  },
  gameGridMeta: {
    fontSize: 10,
    fontWeight: "500",
  },
  gameGridTime: {
    fontSize: 10,
    fontWeight: "500",
  },
  leagueSection: {
    marginBottom: spacing.xs + 2,
  },
  leagueHeader: {
    fontSize: 13,
    fontWeight: "700",
    marginBottom: spacing.xs + 2,
  },
  gameCard: {
    marginBottom: spacing.sm + 2,
  },
  gameBody: {
    flexDirection: "row",
    alignItems: "center",
  },
  gameTeams: {
    flex: 1,
    gap: spacing.xs,
  },
  gameTeamRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  gameTeamDot: {
    width: spacing.ml,
    height: spacing.ml,
    borderRadius: radius.sm,
  },
  gameTeamName: {
    fontSize: 14,
    fontWeight: "500",
    flex: 1,
  },
  gameAddBtn: {
    width: spacing.lg,
    height: spacing.lg,
    borderRadius: radius.full,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: spacing.sm,
  },
  gameFooter: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    marginTop: spacing.xxs,
    paddingLeft: 28,
  },
  gameFooterText: {
    fontSize: 10,
    fontWeight: "500",
  },
  gameFooterDot: {
    fontSize: 10,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginHorizontal: spacing.ms,
    marginVertical: spacing.sm,
    paddingHorizontal: spacing.sm + 2,
    borderRadius: radius.md,
    height: 34,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    padding: 0,
  },
  dateSliderWrap: {
    height: 46,
    zIndex: 1,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 6,
    elevation: 5,
  },
  dateRow: {
    paddingHorizontal: spacing.ms,
    alignItems: "center",
    paddingVertical: spacing.sm + 2,
    gap: spacing.xs + 2,
  },
  dateItem: {
    paddingVertical: 5,
    paddingHorizontal: spacing.sm + 2,
    borderRadius: radius.md,
    borderWidth: 1,
  },
  dateText: {
    fontSize: 12,
    fontWeight: "600",
  },
  tabBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
  },
  tabRow: {
    flexDirection: "row",
    gap: spacing.sm + 2,
  },
  tab: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
  },
  tabLabel: {
    fontWeight: "600",
    fontSize: 12,
  },
  sortRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: spacing.sm,
  },
  sortBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs + 2,
  },
  sortLabel: {
    fontSize: 12,
    fontWeight: "500",
  },
  viewModeBtn: {
    padding: spacing.xs,
  },
  sortSheet: {
    paddingHorizontal: spacing.ml,
    paddingTop: spacing.sm,
    paddingBottom: 34,
  },
  sortSheetTitle: {
    fontSize: 14,
    fontWeight: "600",
    marginBottom: spacing.ml,
  },
  sortSheetItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: spacing.md,
  },
  sortSheetItemText: {
    fontSize: 17,
    fontWeight: "500",
  },
  sortSheetCancel: {
    alignItems: "center",
    marginTop: spacing.md,
    paddingVertical: spacing.ms,
  },
  sortSheetCancelText: {
    fontSize: 16,
    fontWeight: "500",
  },
});
